# Generated by Django 4.0.4 on 2022-04-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_cover_category_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('cover', models.ImageField(upload_to='books')),
                ('format_book', models.CharField(choices=[('lesson', 'Lesson'), ('visuals', 'Visuals')], default='lesson', max_length=20)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='Файл фото')),
                ('collateral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_files', to='main.book')),
            ],
            options={
                'verbose_name': 'Book File',
                'verbose_name_plural': 'Book Files',
            },
        ),
    ]
