# Generated by Django 4.0.4 on 2022-04-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_bookfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
    ]
