# Generated by Django 4.0.4 on 2022-04-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookfile',
            old_name='collateral',
            new_name='book',
        ),
    ]
