# Generated by Django 4.0.4 on 2022-04-25 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_collateral_bookfile_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='format_book',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='main.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookfile',
            name='format_book',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('visuals', 'Visuals')], default='lesson', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='This field autofill', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='file',
            field=models.ImageField(upload_to='books', verbose_name='Book file'),
        ),
    ]
