# Generated by Django 4.0.4 on 2022-04-25 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='text',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Text'),
        ),
    ]
