# Generated by Django 4.0.4 on 2022-04-25 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_book_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfile',
            name='file',
            field=models.FileField(upload_to='books', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Book file'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='format_book',
            field=models.CharField(choices=[('lesson', 'Lesson Text'), ('visuals', 'Visuals')], default='lesson', max_length=20),
        ),
    ]
