# Generated by Django 4.0.4 on 2022-04-25 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bookfile_file_alter_bookfile_format_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='', upload_to='books', verbose_name='Image for book'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='file',
            field=models.FileField(upload_to='books_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Book file'),
        ),
    ]
