# Generated by Django 4.0.4 on 2022-04-29 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('main', '0010_book_cover_alter_bookfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFlatePage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
                ('cover', models.ImageField(default='', upload_to='flatpages', verbose_name='Image for page')),
            ],
            bases=('flatpages.flatpage',),
        ),
    ]
