# Generated by Django 4.0.4 on 2022-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_customflatepage_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('agreement', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Сбор заявок с сайта',
                'verbose_name_plural': 'Сбор заявок с сайта',
            },
        ),
    ]
