# Generated by Django 4.0.4 on 2022-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format_book', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], default='instagram', max_length=255)),
                ('link', models.URLField(default='')),
            ],
            options={
                'verbose_name': 'Book File',
                'verbose_name_plural': 'Book Files',
            },
        ),
    ]
