# Generated by Django 4.0.4 on 2022-05-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Social media', 'verbose_name_plural': 'Social medias'},
        ),
    ]
