# Generated by Django 4.0.4 on 2022-05-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_sociallink_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
